[build-system]
requires = ["maturin>=1.9.3,<2.0"]
build-backend = "maturin"

[project]
name = "gruff"
version = "0.0.4"
description = "An opinionated deterministic maintainability linter for Python"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Quality Assurance",
]

[project.urls]
Changelog = "https://github.com/wkentaro/gruff/blob/main/CHANGELOG.md"
Documentation = "https://wkentaro.github.io/gruff/"
Issues = "https://github.com/wkentaro/gruff/issues"
Repository = "https://github.com/wkentaro/gruff"

[tool.maturin]
bindings = "bin"
strip = true

[tool.ruff]
target-version = "py310"

[tool.ruff.lint]
select = [
    "ANN",
    "E",
    "F",
    "I",
    "UP",
]

[tool.ruff.lint.isort]
force-single-line = true

[tool.gruff.lint]
select = ["GR"]

[tool.towncrier]
directory = "changelog.d"
filename = "CHANGELOG.md"
title_format = "## {version} - {project_date}"
issue_format = "[#{issue}](https://github.com/wkentaro/gruff/pull/{issue})"
ignore = ["README.md"]
type = [
  { directory = "added", name = "Added", showcontent = true },
  { directory = "changed", name = "Changed", showcontent = true },
  { directory = "deprecated", name = "Deprecated", showcontent = true },
  { directory = "removed", name = "Removed", showcontent = true },
  { directory = "fixed", name = "Fixed", showcontent = true },
  { directory = "security", name = "Security", showcontent = true },
]
