name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - name: Check Python formatting
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6
        with:
          args: format --check
          version: "0.16.4"
      - name: Lint Python
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6
        with:
          version: "0.16.4"
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - run: cargo run --locked -- check .
